DROP TABLE if exists users;
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    birth_date TIMESTAMP,
    PRIMARY KEY (id)
);



INSERT INTO users (first_name, last_name, email, birth_date) VALUES ('John', 'Doe', 'john.doe@example.com', '1990-01-15');
INSERT INTO users (first_name, last_name, email, birth_date) VALUES ('Jane', 'Smith', 'jane.smith@example.com', '1985-08-22');

